//auth.js
export const SET_CURRENT_USER = "SET_CURRENT_USER" //all in auth 
export const CLEAR_CURRENT_USER= "CLEAR_CURRENT_USER"
export const LOADING_CURRENT_USER = "LOADING_CURRENT_USER"

// entries.js
export const LOADING_ENTRIES = "LOADING_ENTRIES" //entries
export const ENTRIES_LOADED = "ENTRIES_LOADED" //entries
export const ADD_NEW_ENTRY = "ADD_NEW_ENTRY" //auth
export const UPDATE_ENTRY = "UPDATE_ENTRY" //auth
export const DELETE_ENTRY = "DELETE_ENTRY" //auth
export const CLEAR_ENTRIES = "CLEAR_ENTRIES" //ENTRIES 

// //entryForm.js
export const UPDATE_ENTRY_FORM = "UPDATE_ENTRY_FORM"
export const RESET_ENTRY_FORM = "RESET_ENTRY_FORM"

// //loginForm.js
export const UPDATE_LOGIN_FORM = "UPDATE_LOGIN_FORM"
export const RESET_LOGIN_FORM = "RESET_LOGIN_FORM"

// //signupForm.js
export const UPDATE_SIGNUP_FORM = "UPDATE_SIGNUP_FORM"
export const RESET_SIGNUP_FORM = "RESET_SIGNUP_FORM"

// //updateForm.js
export const SET_FORM_DATA_FOR_EDIT = "SET_FORM_DATA_FOR_EDIT"
export const UPDATE_EDITED_ENTRY = "UPDATE_EDITED_ENTRY"
export const RESET_EDIT_FORM = "RESET_EDIT_FORM"

// //users.js
export const LOADING_ALL_USERS_NAMES = "LOADING_ALL_USERS_NAMES"
export const ALL_USERS_LOADED = "ALL_USERS_LOADED"

//memories.js
export const UPDATE_MEMORY_FORM="UPDATE_MEMORY_FORM"
export const RESET_MEMORY_FORM="RESET_MEMORY_FORM"

//descriptionEditForm.js
export const UPDATE_DESCRIPTION_FORM = "UPDATE_DESCRIPTION_FORM"
export const RESET_DESCRIPTION_FORM = "RESET_DESCRIPTION_FORM"
export const SET_DESCRIPTION_DATA_FOR_EDIT = "SET_DESCRIPTION_DATA_FOR_EDIT"



